name: "AG's PR summarizer"
description: "AI Pull Request summarization"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT"
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model to use"
    required: false
    default: "gpt-4o"
  exclude:
    description: "Glob patterns to exclude files from the analysis (comma-separated)"
    required: false
    default: "**/*.lock,dist/**/*,**/*.min.js,**/*.map"
  max_files:
    description: "Maximum number of files to analyze per PR"
    required: false
    default: "50"
  owner:
    description: "Who should own the summary: 'bot' (appears as GitHub Action comment) or 'author' (appears in PR description as the PR author)"
    required: false
    default: "author"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "git-pull-request"
  color: "purple"
