name: "PR Summarizer"
description: "AI-powered Pull Request summarization and code review using OpenAI GPT"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT"
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model to use"
    required: false
    default: "gpt-4-turbo-preview"
  exclude:
    description: "Glob patterns to exclude files from the analysis (comma-separated)"
    required: false
    default: "*.lock,dist/**,*.min.js,*.map"
  max_files:
    description: "Maximum number of files to analyze per PR"
    required: false
    default: "50"
  comment_type:
    description: "Type of comment to make (review or comment)"
    required: false
    default: "review"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "git-pull-request"
  color: "purple"
